
#==============================================================================
# START!!! 905_predict_1015-4.py    PID: 3881    time: 2018-10-15 10:05:19.696306
#==============================================================================

SEED: 3130
../data/train_f001.f
../data/train_f002.f
../data/train_f003.f
../data/train_f004.f
../data/train_f005.f
../data/train_f701.f
  0%|          | 0/6 [00:00<?, ?it/s]100%|██████████| 6/6 [00:05<00:00,  1.05it/s]
no dup :) 
X.shape (7848, 424)
CV auc-mean: 0.9207714815315068 + 0.011632140318120444
  0%|          | 0/6 [00:00<?, ?it/s] 83%|████████▎ | 5/6 [01:04<00:12, 12.84s/it]100%|██████████| 6/6 [01:04<00:00, 10.71s/it]
  0%|          | 0/8 [00:00<?, ?it/s] 12%|█▎        | 1/8 [01:07<07:55, 67.97s/it] 25%|██▌       | 2/8 [02:12<06:36, 66.14s/it] 38%|███▊      | 3/8 [03:15<05:26, 65.33s/it] 50%|█████     | 4/8 [04:20<04:20, 65.15s/it] 62%|██████▎   | 5/8 [05:29<03:17, 65.92s/it] 75%|███████▌  | 6/8 [06:39<02:13, 66.64s/it] 88%|████████▊ | 7/8 [07:51<01:07, 67.36s/it]100%|██████████| 8/8 [09:01<00:00, 67.68s/it]
Traceback (most recent call last):
  File "905_predict_1015-4.py", line 224, in <module>
    raise
RuntimeError: No active exception to reraise
